version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: baldecash_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: baldecash_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d baldecash_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./prueba-tecnica-back
      dockerfile: Dockerfile
    container_name: baldecash_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/baldecash_db?schema=public
      - PORT=3000
      - ANNUAL_RATE=0.24
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./prueba-front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3000
    container_name: baldecash_frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - PORT=3001
    depends_on:
      - backend

volumes:
  postgres_data:
